image:
  repository: postgres
  tag: "14.5"
  pullPolicy: IfNotPresent

auth:
  postgresPassword: "password"
  database: "database"
  username: "username"

persistence:
  enabled: true
  size: 4Gi

service:
  type: ClusterIP
  port: 5432

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
namespace: dev
