apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "redis.fullname" . }}-{{ .Values.namespace }}-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/redis
  storageClassName: ""
