---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClass }}-{{ .Values.namespace }}
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  onDelete: "retain"
  pathPattern: "${.PVC.annotations.nfs.io/storage-path}"
